name: Node CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install, Build and Deploy
      run: |
        npm install
        git config user.email hello@matteocollina.com
        git config user.name "Matteo Collina"
        npx gulp deploy
      env:
        CI: true
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
